// Generated by `bun init`

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV: "development" | "production" | "test";
      BUN_PUBLIC_API_ORIGIN: string;
      BUN_PUBLIC_API_PORT: string;
      BUN_PUBLIC_APP_PORT: string;
      BUN_PUBLIC_ADSENSE_CLIENT: string;
      BUN_PUBLIC_ADSENSE_SLOT: string;
      BUN_PUBLIC_ADS_ENABLED: string;
      BUN_PUBLIC_ADS_GUESTS_ONLY: string;
    }
  }
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
